export const GOLD_NISAB_GRAMS=87.48,SILVER_NISAB_GRAMS=612.36,ZAKAT_RATE=.025;
export type EquityMethod='full'|'proxy'|'verified';
export type Holding={cash:number;equity:number;fixed:number;other:number;equityMethod:EquityMethod;proxy:number};
export type Reg=Holding&{enabled:boolean;access:'yes'|'no'|'unsure';tax:number};
export type Data={lang:'en'|'fr';selected:Record<string,boolean>;date:string;nisab:'silver'|'gold';prices:{silver:number;gold:number;btc:number;eth:number;asOf:string};bank:{cash:number};registered:{tfsa:Reg;rrsp:Reg;resp:Reg;fhsa:Reg;other:Reg};nonreg:Holding&{cryptoCad:number;btcQty:number;ethQty:number};metals:{gold:number;goldUnit:string;silver:number;silverUnit:string};property:{rent:number;resale:number};owed:{amount:number};business:{cash:number;inventory:number;invoices:number;obligations:number};debts:{cards:number;bills:number;tax:number;loans:number;mortgage:number;other:number}};
const hold=():Holding=>({cash:0,equity:0,fixed:0,other:0,equityMethod:'full',proxy:30});const reg=():Reg=>({enabled:false,...hold(),access:'yes',tax:0});
export const initial=():Data=>({lang:'en',selected:{bank:true,registered:false,nonreg:false,metals:false,property:false,owed:false,business:false,debts:false},date:new Date().toISOString().slice(0,10),nisab:'silver',prices:{silver:0,gold:0,btc:0,eth:0,asOf:''},bank:{cash:0},registered:{tfsa:reg(),rrsp:{...reg(),tax:30},resp:{...reg(),access:'unsure'},fhsa:reg(),other:{...reg(),access:'unsure'}},nonreg:{...hold(),cryptoCad:0,btcQty:0,ethQty:0},metals:{gold:0,goldUnit:'g',silver:0,silverUnit:'g'},property:{rent:0,resale:0},owed:{amount:0},business:{cash:0,inventory:0,invoices:0,obligations:0},debts:{cards:0,bills:0,tax:0,loans:0,mortgage:0,other:0}});
const grams=(n:number,u:string)=>n*({g:1,oz:31.1034768,tola:11.6638,kg:1000}[u]||1);const equity=(v:number,m:EquityMethod,p:number)=>v*(m==='full'?1:p/100);const holding=(h:Holding)=>h.cash+h.fixed+h.other+equity(h.equity,h.equityMethod,h.proxy);const regValue=(r:Reg)=>!r.enabled||r.access==='no'?0:holding(r)*(1-r.tax/100);
export function calculate(d:Data){const bank=d.selected.bank?d.bank.cash:0;const registered=d.selected.registered?Object.values(d.registered).reduce((s,r)=>s+regValue(r),0):0;const crypto=d.nonreg.cryptoCad+d.nonreg.btcQty*d.prices.btc+d.nonreg.ethQty*d.prices.eth;const nonreg=d.selected.nonreg?holding(d.nonreg)+crypto:0;const metals=d.selected.metals?grams(d.metals.gold,d.metals.goldUnit)*d.prices.gold+grams(d.metals.silver,d.metals.silverUnit)*d.prices.silver:0;const property=d.selected.property?d.property.rent+d.property.resale:0,owed=d.selected.owed?d.owed.amount:0,business=d.selected.business?d.business.cash+d.business.inventory+d.business.invoices:0,liabilities=(d.selected.business?d.business.obligations:0)+(d.selected.debts?Object.values(d.debts).reduce((a,b)=>a+b,0):0);const assets=bank+registered+nonreg+metals+property+owed+business,net=Math.max(0,assets-liabilities),silverNisab=SILVER_NISAB_GRAMS*d.prices.silver,goldNisab=GOLD_NISAB_GRAMS*d.prices.gold,threshold=d.nisab==='silver'?silverNisab:goldNisab,complete=threshold>0,due=complete&&net>=threshold;return{bank,registered,nonreg,crypto,metals,property,owed,business,liabilities,assets,net,silverNisab,goldNisab,threshold,complete,due,zakat:due?net*ZAKAT_RATE:0}}
